### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by charleswu52** [apollo008/orchid-fst#1]
OS：Ubuntu18.04 64bit
在执行 **cmake -DENABLE_BUILD_SHARE=ON ../src** 命令的时候报错：

Making all in DllPlugInTester
make[2]: 进入目录“/home/xx/orchid-fst.git/build-dir/share/cppunit/cppunit-1.12.1/src/DllPlugInTester”
g++ -DHAVE_CONFIG_H -I. -I../../config -I../../include -I../../include    -D_GLIBCXX_USE_CXX11_ABI=1 -MT DllPlugInTester.o -MD -MP -MF .deps/DllPlugInTester.Tpo -c -o DllPlugInTester.o DllPlugInTester.cpp
mv -f .deps/DllPlugInTester.Tpo .deps/DllPlugInTester.Po
g++ -DHAVE_CONFIG_H -I. -I../../config -I../../include -I../../include    -D_GLIBCXX_USE_CXX11_ABI=1 -MT CommandLineParser.o -MD -MP -MF .deps/CommandLineParser.Tpo -c -o CommandLineParser.o CommandLineParser.cpp
mv -f .deps/CommandLineParser.Tpo .deps/CommandLineParser.Po
/bin/sh ../../libtool --tag=CXX   --mode=link g++  -D_GLIBCXX_USE_CXX11_ABI=1 -ldl  -o DllPlugInTester DllPlugInTester.o CommandLineParser.o ../../src/cppunit/libcppunit.la -lm
mkdir .libs
g++ -D_GLIBCXX_USE_CXX11_ABI=1 -o .libs/DllPlugInTester DllPlugInTester.o CommandLineParser.o  -ldl ../../src/cppunit/.libs/libcppunit.so -lm  -Wl,--rpath -Wl,/home/charles/local/lib
../../src/cppunit/.libs/libcppunit.so: undefined reference to `dlopen'
../../src/cppunit/.libs/libcppunit.so: undefined reference to `dlclose'
../../src/cppunit/.libs/libcppunit.so: undefined reference to `dlsym'
collect2: error: ld returned 1 exit status
Makefile:321: recipe for target 'DllPlugInTester' failed

还有后面的：

Making install in DllPlugInTester
make[2]: 进入目录“/home/xx/orchid-fst.git/build-dir/share/cppunit/cppunit-1.12.1/src/DllPlugInTester”
/bin/sh ../../libtool --tag=CXX   --mode=link g++  -D_GLIBCXX_USE_CXX11_ABI=1 -ldl  -o DllPlugInTester DllPlugInTester.o CommandLineParser.o ../../src/cppunit/libcppunit.la -lm
g++ -D_GLIBCXX_USE_CXX11_ABI=1 -o .libs/DllPlugInTester DllPlugInTester.o CommandLineParser.o  -ldl ../../src/cppunit/.libs/libcppunit.so -lm  -Wl,--rpath -Wl,/home/charles/local/lib
../../src/cppunit/.libs/libcppunit.so: undefined reference to `dlopen'
../../src/cppunit/.libs/libcppunit.so: undefined reference to `dlclose'
../../src/cppunit/.libs/libcppunit.so: undefined reference to `dlsym'
collect2: error: ld returned 1 exit status
Makefile:321: recipe for target 'DllPlugInTester' failed
make[2]: 离开目录“/home/xx/orchid-fst.git/build-dir/share/cppunit/cppunit-1.12.1/src/DllPlugInTester”
make[2]: *** [DllPlugInTester] Error 1
Makefile:243: recipe for target 'install-recursive' failed
make[1]: 离开目录“/home/xx/orchid-fst.git/build-dir/share/cppunit/cppunit-1.12.1/src”
make[1]: *** [install-recursive] Error 1
Makefile:443: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1

**Comment by apollo008** [comment]
vim src/CMakeLists.txt
修改第11行从原来的set(${TOP_PROJECT_NAME_UPPER}_DEPEND_PREFIX_DIR $ENV{HOME}/local)   #need set改为 set(${TOP_PROJECT_NAME_UPPER}_DEPEND_PREFIX_DIR /home/xx/local)   #need set
/home/xx/local 是你机器上真实存在的目录。
gcc 需要在gcc 7及以上

**Comment by charleswu52** [comment]
/home/xx/local 是你机器上真实存在的目录。我设置了，没问题的，只是在这里我隐去了。

**Comment by charleswu52** [comment]
研究一晚上还是没有解决， 能给解答一下吗 @apollo008

**Comment by apollo008** [comment]
I see you have solved the compilation problem since then. Okay.

**Comment by charleswu52** [comment]
> I see you have solved the compilation problem since then. Okay.

Yes! It's OK! But there are still some bugs in the algorithm, I am testing and reading the source code.
